pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }


         stage('Deploy Application on Remote Docker VM') {
            steps {
                // Utilisation directe du credential username + private key
                ansiblePlaybook(
                    playbook: 'deployment/ansible/deploy.yml',
                    inventory: 'deployment/ansible/hosts.ini',
                    credentialsId: 'ssh-user-pass' // ton credential Jenkins
                )
            }
        }
    }
    }

    post {
        success {
            echo "Déploiement local terminé avec succès !"
        }
        failure {
            echo "Le déploiement local a échoué à se terminer." // j
            echo "Vérifiez les journaux pour plus de détails."
        }
    }


}