pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Deploy Application on Remote Docker VM') {
            steps {
                // Utilisation directe du credential username + private 
                ansiblePlaybook(
                    playbook: 'deployment/ansible/deploy.yml',
                    inventory: 'deployment/ansible/hosts.ini',
                    credentialsId: 'ssh-user-pass' 
                )
            }
        }
    }

    post {
        success {
            echo "Déploiement sur la VM Docker terminé avec succès !"
        }
        failure {
            echo "Le déploiement sur la VM Docker a échoué."
            echo "Vérifiez les journaux pour plus de détails."
        }
    }
}
