---
- name: Déployer l'application Tombo en local
  hosts: local
  become: true
  vars:
    app_path: "{{ playbook_dir }}/.."  # remonte d'un niveau pour accéder au docker-compose.yml
  tasks:

    - name: Installer Docker et Docker Compose (Debian/Ubuntu)
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes
      become: true

    - name: Lancer l'application via Docker Compose
      shell: |
        docker-compose down
        docker-compose up -d --build
      args:
        chdir: "{{ app_path }}"
      become: true
