---
- name: Déployer l'application Tombo en local
  hosts: local
  vars:
    app_path: "{{ playbook_dir }}/.."  # remonte d'un niveau pour accéder au docker-compose.yml
  tasks:

    
    - name: Lancer l'application via Docker Compose
      shell: |
        docker-compose down
        docker-compose up -d --build
      args:
        chdir: "{{ app_path }}"
      become: true
