---
- name: Déployer l'application Tombo sur la VM Docker
  hosts: remote
  vars:
    local_app_path: "{{ playbook_dir }}/../.."          # chemin sur Jenkins
    remote_app_path: "/home/ubuntu/tombo-app"       # chemin sur la VM distante
  tasks:

  
    - name: Copier le projet sur la VM distante
      synchronize:
        src: "{{ local_app_path }}/"
        dest: "{{ remote_app_path }}/"
        delete: yes    
        recursive: yes
      become: true

    - name: Stopper les conteneurs existants
      shell: docker compose down
      args:
        chdir: "{{ remote_app_path }}"

    - name: Rebuild frontend sans cache
      shell: docker compose build --no-cache tombo-frontend
      args:
        chdir: "{{ remote_app_path }}"

    - name: Rebuild backend sans cache
      shell: docker compose build --no-cache tomoghik
      args:
        chdir: "{{ remote_app_path }}"

    - name: Rebuild car-proxy sans cache
      shell: docker compose build --no-cache car-proxy
      args:
        chdir: "{{ remote_app_path }}"

    - name: Lancer Docker Compose avec les nouvelles images
      shell: docker compose up -d
      args:
        chdir: "{{ remote_app_path }}"
